name: Build Release APK

on:
  push:
    branches:
      - realtime  # Trigger the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - realtime

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java 11)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Make gradlew executable
      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      # Step 4: Build the release APK
      - name: Build release APK
        run: ./gradlew assembleRelease

      # Step 5: Upload release APK
      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
